/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EWasteRouteImport } from './routes/e-waste'
import { Route as EcoAssistRouteImport } from './routes/eco-assist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PickupsRouteImport } from './routes/pickups'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecyclingRouteImport } from './routes/recycling'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCentresRouteImport } from './routes/admin.centres'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AwarenessIndexRouteImport } from './routes/awareness.index'
import { Route as AwarenessIdRouteImport } from './routes/awareness.$id'
import { Route as CentreCollectionsRouteImport } from './routes/centre.collections'
import { Route as CentreDashboardRouteImport } from './routes/centre.dashboard'
import { Route as CentreRequestsRouteImport } from './routes/centre.requests'
import { Route as CentreTransfersRouteImport } from './routes/centre.transfers'
import { Route as CentresIndexRouteImport } from './routes/centres.index'
import { Route as CentresIdRouteImport } from './routes/centres.$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCentresRouteImport } from './routes/dashboard.centres'
import { Route as EWasteIndexRouteImport } from './routes/e-waste.index'
import { Route as EWasteAddRouteImport } from './routes/e-waste.add'
import { Route as PickupRequestRouteImport } from './routes/pickup.request'
import { Route as PickupsIndexRouteImport } from './routes/pickups.index'
import { Route as PickupsIdRouteImport } from './routes/pickups.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EWasteRoute = EWasteRouteImport.update({
  id: '/e-waste',
  path: '/e-waste',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoAssistRoute = EcoAssistRouteImport.update({
  id: '/eco-assist',
  path: '/eco-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsRoute = PickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclingRoute = RecyclingRouteImport.update({
  id: '/recycling',
  path: '/recycling',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCentresRoute = AdminCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AwarenessIndexRoute = AwarenessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AwarenessRoute,
} as any)
const AwarenessIdRoute = AwarenessIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AwarenessRoute,
} as any)
const CentreCollectionsRoute = CentreCollectionsRouteImport.update({
  id: '/centre/collections',
  path: '/centre/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreDashboardRoute = CentreDashboardRouteImport.update({
  id: '/centre/dashboard',
  path: '/centre/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreRequestsRoute = CentreRequestsRouteImport.update({
  id: '/centre/requests',
  path: '/centre/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreTransfersRoute = CentreTransfersRouteImport.update({
  id: '/centre/transfers',
  path: '/centre/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresIndexRoute = CentresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentresRoute,
} as any)
const CentresIdRoute = CentresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CentresRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCentresRoute = DashboardCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => DashboardRoute,
} as any)
const EWasteIndexRoute = EWasteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EWasteRoute,
} as any)
const EWasteAddRoute = EWasteAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => EWasteRoute,
} as any)
const PickupRequestRoute = PickupRequestRouteImport.update({
  id: '/pickup/request',
  path: '/pickup/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsIndexRoute = PickupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PickupsRoute,
} as any)
const PickupsIdRoute = PickupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PickupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awareness': typeof AwarenessRouteWithChildren
  '/centres': typeof CentresRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/e-waste': typeof EWasteRouteWithChildren
  '/eco-assist': typeof EcoAssistRoute
  '/login': typeof LoginRoute
  '/pickups': typeof PickupsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recycling': typeof RecyclingRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/admin/users': typeof AdminUsersRoute
  '/awareness/$id': typeof AwarenessIdRoute
  '/centre/collections': typeof CentreCollectionsRoute
  '/centre/dashboard': typeof CentreDashboardRoute
  '/centre/requests': typeof CentreRequestsRoute
  '/centre/transfers': typeof CentreTransfersRoute
  '/centres/$id': typeof CentresIdRoute
  '/dashboard/centres': typeof DashboardCentresRoute
  '/e-waste/add': typeof EWasteAddRoute
  '/pickup/request': typeof PickupRequestRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/awareness/': typeof AwarenessIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/e-waste/': typeof EWasteIndexRoute
  '/pickups/': typeof PickupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eco-assist': typeof EcoAssistRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recycling': typeof RecyclingRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/admin/users': typeof AdminUsersRoute
  '/awareness/$id': typeof AwarenessIdRoute
  '/centre/collections': typeof CentreCollectionsRoute
  '/centre/dashboard': typeof CentreDashboardRoute
  '/centre/requests': typeof CentreRequestsRoute
  '/centre/transfers': typeof CentreTransfersRoute
  '/centres/$id': typeof CentresIdRoute
  '/dashboard/centres': typeof DashboardCentresRoute
  '/e-waste/add': typeof EWasteAddRoute
  '/pickup/request': typeof PickupRequestRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/admin': typeof AdminIndexRoute
  '/awareness': typeof AwarenessIndexRoute
  '/centres': typeof CentresIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/e-waste': typeof EWasteIndexRoute
  '/pickups': typeof PickupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awareness': typeof AwarenessRouteWithChildren
  '/centres': typeof CentresRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/e-waste': typeof EWasteRouteWithChildren
  '/eco-assist': typeof EcoAssistRoute
  '/login': typeof LoginRoute
  '/pickups': typeof PickupsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recycling': typeof RecyclingRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/admin/users': typeof AdminUsersRoute
  '/awareness/$id': typeof AwarenessIdRoute
  '/centre/collections': typeof CentreCollectionsRoute
  '/centre/dashboard': typeof CentreDashboardRoute
  '/centre/requests': typeof CentreRequestsRoute
  '/centre/transfers': typeof CentreTransfersRoute
  '/centres/$id': typeof CentresIdRoute
  '/dashboard/centres': typeof DashboardCentresRoute
  '/e-waste/add': typeof EWasteAddRoute
  '/pickup/request': typeof PickupRequestRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/awareness/': typeof AwarenessIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/e-waste/': typeof EWasteIndexRoute
  '/pickups/': typeof PickupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/awareness'
    | '/centres'
    | '/dashboard'
    | '/e-waste'
    | '/eco-assist'
    | '/login'
    | '/pickups'
    | '/profile'
    | '/recycling'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/admin/analytics'
    | '/admin/centres'
    | '/admin/users'
    | '/awareness/$id'
    | '/centre/collections'
    | '/centre/dashboard'
    | '/centre/requests'
    | '/centre/transfers'
    | '/centres/$id'
    | '/dashboard/centres'
    | '/e-waste/add'
    | '/pickup/request'
    | '/pickups/$id'
    | '/admin/'
    | '/awareness/'
    | '/centres/'
    | '/dashboard/'
    | '/e-waste/'
    | '/pickups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eco-assist'
    | '/login'
    | '/profile'
    | '/recycling'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/admin/analytics'
    | '/admin/centres'
    | '/admin/users'
    | '/awareness/$id'
    | '/centre/collections'
    | '/centre/dashboard'
    | '/centre/requests'
    | '/centre/transfers'
    | '/centres/$id'
    | '/dashboard/centres'
    | '/e-waste/add'
    | '/pickup/request'
    | '/pickups/$id'
    | '/admin'
    | '/awareness'
    | '/centres'
    | '/dashboard'
    | '/e-waste'
    | '/pickups'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/awareness'
    | '/centres'
    | '/dashboard'
    | '/e-waste'
    | '/eco-assist'
    | '/login'
    | '/pickups'
    | '/profile'
    | '/recycling'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/admin/analytics'
    | '/admin/centres'
    | '/admin/users'
    | '/awareness/$id'
    | '/centre/collections'
    | '/centre/dashboard'
    | '/centre/requests'
    | '/centre/transfers'
    | '/centres/$id'
    | '/dashboard/centres'
    | '/e-waste/add'
    | '/pickup/request'
    | '/pickups/$id'
    | '/admin/'
    | '/awareness/'
    | '/centres/'
    | '/dashboard/'
    | '/e-waste/'
    | '/pickups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwarenessRoute: typeof AwarenessRouteWithChildren
  CentresRoute: typeof CentresRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EWasteRoute: typeof EWasteRouteWithChildren
  EcoAssistRoute: typeof EcoAssistRoute
  LoginRoute: typeof LoginRoute
  PickupsRoute: typeof PickupsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecyclingRoute: typeof RecyclingRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  CentreCollectionsRoute: typeof CentreCollectionsRoute
  CentreDashboardRoute: typeof CentreDashboardRoute
  CentreRequestsRoute: typeof CentreRequestsRoute
  CentreTransfersRoute: typeof CentreTransfersRoute
  PickupRequestRoute: typeof PickupRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-waste': {
      id: '/e-waste'
      path: '/e-waste'
      fullPath: '/e-waste'
      preLoaderRoute: typeof EWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-assist': {
      id: '/eco-assist'
      path: '/eco-assist'
      fullPath: '/eco-assist'
      preLoaderRoute: typeof EcoAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups': {
      id: '/pickups'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof PickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycling': {
      id: '/recycling'
      path: '/recycling'
      fullPath: '/recycling'
      preLoaderRoute: typeof RecyclingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/centres': {
      id: '/admin/centres'
      path: '/centres'
      fullPath: '/admin/centres'
      preLoaderRoute: typeof AdminCentresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/awareness/': {
      id: '/awareness/'
      path: '/'
      fullPath: '/awareness/'
      preLoaderRoute: typeof AwarenessIndexRouteImport
      parentRoute: typeof AwarenessRoute
    }
    '/awareness/$id': {
      id: '/awareness/$id'
      path: '/$id'
      fullPath: '/awareness/$id'
      preLoaderRoute: typeof AwarenessIdRouteImport
      parentRoute: typeof AwarenessRoute
    }
    '/centre/collections': {
      id: '/centre/collections'
      path: '/centre/collections'
      fullPath: '/centre/collections'
      preLoaderRoute: typeof CentreCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre/dashboard': {
      id: '/centre/dashboard'
      path: '/centre/dashboard'
      fullPath: '/centre/dashboard'
      preLoaderRoute: typeof CentreDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre/requests': {
      id: '/centre/requests'
      path: '/centre/requests'
      fullPath: '/centre/requests'
      preLoaderRoute: typeof CentreRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre/transfers': {
      id: '/centre/transfers'
      path: '/centre/transfers'
      fullPath: '/centre/transfers'
      preLoaderRoute: typeof CentreTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/': {
      id: '/centres/'
      path: '/'
      fullPath: '/centres/'
      preLoaderRoute: typeof CentresIndexRouteImport
      parentRoute: typeof CentresRoute
    }
    '/centres/$id': {
      id: '/centres/$id'
      path: '/$id'
      fullPath: '/centres/$id'
      preLoaderRoute: typeof CentresIdRouteImport
      parentRoute: typeof CentresRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/centres': {
      id: '/dashboard/centres'
      path: '/centres'
      fullPath: '/dashboard/centres'
      preLoaderRoute: typeof DashboardCentresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/e-waste/': {
      id: '/e-waste/'
      path: '/'
      fullPath: '/e-waste/'
      preLoaderRoute: typeof EWasteIndexRouteImport
      parentRoute: typeof EWasteRoute
    }
    '/e-waste/add': {
      id: '/e-waste/add'
      path: '/add'
      fullPath: '/e-waste/add'
      preLoaderRoute: typeof EWasteAddRouteImport
      parentRoute: typeof EWasteRoute
    }
    '/pickup/request': {
      id: '/pickup/request'
      path: '/pickup/request'
      fullPath: '/pickup/request'
      preLoaderRoute: typeof PickupRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups/': {
      id: '/pickups/'
      path: '/'
      fullPath: '/pickups/'
      preLoaderRoute: typeof PickupsIndexRouteImport
      parentRoute: typeof PickupsRoute
    }
    '/pickups/$id': {
      id: '/pickups/$id'
      path: '/$id'
      fullPath: '/pickups/$id'
      preLoaderRoute: typeof PickupsIdRouteImport
      parentRoute: typeof PickupsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCentresRoute: typeof AdminCentresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCentresRoute: AdminCentresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AwarenessRouteChildren {
  AwarenessIdRoute: typeof AwarenessIdRoute
  AwarenessIndexRoute: typeof AwarenessIndexRoute
}

const AwarenessRouteChildren: AwarenessRouteChildren = {
  AwarenessIdRoute: AwarenessIdRoute,
  AwarenessIndexRoute: AwarenessIndexRoute,
}

const AwarenessRouteWithChildren = AwarenessRoute._addFileChildren(
  AwarenessRouteChildren,
)

interface CentresRouteChildren {
  CentresIdRoute: typeof CentresIdRoute
  CentresIndexRoute: typeof CentresIndexRoute
}

const CentresRouteChildren: CentresRouteChildren = {
  CentresIdRoute: CentresIdRoute,
  CentresIndexRoute: CentresIndexRoute,
}

const CentresRouteWithChildren =
  CentresRoute._addFileChildren(CentresRouteChildren)

interface DashboardRouteChildren {
  DashboardCentresRoute: typeof DashboardCentresRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCentresRoute: DashboardCentresRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EWasteRouteChildren {
  EWasteAddRoute: typeof EWasteAddRoute
  EWasteIndexRoute: typeof EWasteIndexRoute
}

const EWasteRouteChildren: EWasteRouteChildren = {
  EWasteAddRoute: EWasteAddRoute,
  EWasteIndexRoute: EWasteIndexRoute,
}

const EWasteRouteWithChildren =
  EWasteRoute._addFileChildren(EWasteRouteChildren)

interface PickupsRouteChildren {
  PickupsIdRoute: typeof PickupsIdRoute
  PickupsIndexRoute: typeof PickupsIndexRoute
}

const PickupsRouteChildren: PickupsRouteChildren = {
  PickupsIdRoute: PickupsIdRoute,
  PickupsIndexRoute: PickupsIndexRoute,
}

const PickupsRouteWithChildren =
  PickupsRoute._addFileChildren(PickupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AwarenessRoute: AwarenessRouteWithChildren,
  CentresRoute: CentresRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EWasteRoute: EWasteRouteWithChildren,
  EcoAssistRoute: EcoAssistRoute,
  LoginRoute: LoginRoute,
  PickupsRoute: PickupsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecyclingRoute: RecyclingRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  CentreCollectionsRoute: CentreCollectionsRoute,
  CentreDashboardRoute: CentreDashboardRoute,
  CentreRequestsRoute: CentreRequestsRoute,
  CentreTransfersRoute: CentreTransfersRoute,
  PickupRequestRoute: PickupRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
